# -*- coding: utf-8 -*-
"""Decission_Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EEKYspMuDbAVhlZSfJ7cJiL1MSNuLIZr
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import metrics
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('drug200.csv')
df.head()

df.describe()

df['Drug'].value_counts()

#Codificando features Sex,BP e cholesterol
label_encoder = LabelEncoder()
df['Sex'] = label_encoder.fit_transform(df['Sex'])
df['BP'] = label_encoder.fit_transform(df['BP'])
df['Cholesterol'] = label_encoder.fit_transform(df['Cholesterol'])
df

df.isnull().sum()

custom_map = {'drugA':0,'drugB':1,'drugC':2,'drugX':3,'drugY':4}
df['Drug_num'] = df['Drug'].map(custom_map)
df

df.drop('Drug',axis=1).corr()['Drug_num']

category_counts = df['Drug'].value_counts()

#Grafico de categorias distribuidas
plt.bar(category_counts.index, category_counts.values, color='blue')
plt.xlabel('Drugs')
plt.xticks(rotation=45)
plt.show()

#Variaveis
y = df['Drug']
X = df.drop(['Drug', 'Drug_num'],axis=1)

#Splitando dataset(Aqui seria util usar stratify para aumentar o balanceamento do dataset, o laboratorio não pediu.)
X_trainset, X_testset,y_trainset,y_testset = train_test_split(X,y, test_size=0.3,stratify=y,random_state=32)

drugTree = DecisionTreeClassifier(criterion='entropy',
                                  max_depth=4,
                                  min_samples_leaf=5,
                                  random_state=42)

drugTree.fit(X_trainset,y_trainset)

#Previsão
tree_prediction = drugTree.predict(X_testset)
print(f'Acuracia da árvore: {np.round(100*metrics.accuracy_score(y_testset,tree_prediction),2)}%')
print('\nMETRICS:\n')
print(metrics.classification_report(y_testset, tree_prediction))
metrics.ConfusionMatrixDisplay.from_predictions(y_testset, tree_prediction)
plt.show()

pd.Series(drugTree.feature_importances_,index=X.columns).sort_values(ascending=False)

#Árvore de decisão
plot_tree(drugTree)
plt.show()

"""**Decision criteria:**

Drug A : $Na\_to\_K <= 14.627,\ BP = High,\ Age <= 50.5$<br>
Drug B : $Na\_to\_K <= 14.627,\ BP = High,\ Age > 50.5$<br>
Drug C : $Na\_to\_K <= 14.627,\ BP = Low,\ Cholesterol <= High$<br>
Drug X : $Na\_to\_K <= 14.627,\ BP = Normal,\ Cholesterol = High$

"""

print(sklearn.__version__)